### ISSUE TITLE
Need automatic layout for ladder logic (LD)

### ISSUE THREAD

**Issue by alexchandel** [thiagoralves/OpenPLC_Editor#113] opened 2024-05-06 14:38 UTC
Ladder logic is annoying to position by hand, and all industrial users will expect the components to automatically layout and position themselves.

Please provide the option for automatic (and continuous, reflowing with every edit, new component, and window resize) layout of ladder logic.

**Comment by thiagoralves** [comment] 2024-05-06 17:40
Duplicate of #114

**Closed by thiagoralves** 2024-05-06 17:40 UTC
